### PR TITLE
feat: better feedback when unable to use reflection to create context

### LINKED ISSUE #193: Obscure exceptions when `Value.FromReflection` fails
If you provide a context member in the form of `Value.FromReflection(obj)` and the object contains properties that are incompatible, you get a very obscure exception that hides the real problem point.

I would expect the exception to pinpoint the property that is problematic.

### PR DESCRIPTION
**Pull request by paviad**
When unable to use reflection to interpret a property, throw a special exception that provides information about the property that caused the problem.

Closes #193

### CODE REVIEW

**Review by r3c — COMMENTED** [review]
Thanks for this proposal! Definitely better than current approach 🙂 If that's OK for you I'll add some test coverage on this feature (unless you want to give it a shot) before it can be merged 👍

**Comment by paviad** [comment]
It's definitely ok, go ahead. I'm sorry I didn't think of that before posting.

**Comment by r3c** [comment]
No worries 🙂 Do you have an example of objects holding a property that can't be converted? The checks already in place were trying to avoid ending up in such scenario, so I guess something was missing there as well 🙂

**Comment by paviad** [comment]
Took me a while, but here's a minimal example:

```csharp
public void TestReflectionFail() {
    var problemObj = Encoding.UTF8;
    var context = Context.CreateCustom(new Dictionary<Value, Value> {
        ["problemObj"] = Value.FromReflection(problemObj, BindingFlags.Instance | BindingFlags.Public),
    });
    Document.CreateDefault("{problemObj.foo}").Document.Render(context);
}
```

The call to `Render` throws it.

**Comment by r3c** [comment]
I just discovered `ref struct`s today 🙂 I'm usually trying to avoid exceptions as much as possible in the library due to their absence of type safety, but throwing with an explicit exception here is still better than the opaque type constraint violation, at least until I take the time to figure out how to handle `ReadOnlySpan<byte>` properly 🙂

Here is some simple unit test (had to restrict to 7.0 since `Encoding.Preamble` didn't exist in 6.0) [here](https://github.com/r3c/cottle/commit/ed893f0b1427d3bc840eb217596b832d3efc79fa), can you please tell me if it looks OK to you and push it into your PR so I can approve and close it?

**Comment by paviad** [comment]
This looks good, test passes.

**Review by r3c — APPROVED** [review]

**Pull request merged**
