### PR TITLE
feat: support nullable types in reflection values

### LINKED ISSUE #185: No support for nullable types in reflection value
When using `Value.FromReflection` with an object that has nullable primitive types such as `decimal?` the value cannot be accessed from the template.

Example:

```csharp
var template = "-->{obj.val}<--";
var documentResult = Document.CreateDefault(template);
var document = documentResult.DocumentOrThrow;

var obj = new {
    val = (decimal?)1234
};

var context = Context.CreateBuiltin(new Dictionary<Value, Value> {
    ["obj"] = Value.FromReflection(obj, BindingFlags.Public | BindingFlags.Instance),
});

var result = document.Render(context); // result == "--><--"
```

In the above example, the result should have been `-->1234<--`

### PR DESCRIPTION
**Pull request by paviad**
Fixes #185

### CODE REVIEW

**Review by r3c — APPROVED** [review]
Nice one, thanks! Feel free to merge, I'll take care of adding unit tests to cover this feature 🙂

**Comment by r3c** [comment]
Sorry @paviad I just realized build & test checks were waiting for manual unlock. It should be good now 🙂

**Comment by paviad** [comment]
Not sure if you're talking to me or to other maintainers :) I cannot merge of course.

**Comment by r3c** [comment]
> Not sure if you're talking to me or to other maintainers :) I cannot merge of course.

OK then I failed to configure permissions properly, I would have expected you to be able to merge as soon as PR was approved, sorry for the confusion. I'll take care of adding tests and will ping here when a NuGet is released with your fix 🙂

**Comment by r3c** [comment]
Done and released in [2.0.9](https://github.com/r3c/cottle/releases/tag/2.0.9)! Thanks again for your contribution! 👍

**Pull request merged**
