### PR TITLE
Introduce new `NbCycleMax` configuration option.

### PR DESCRIPTION
**Pull request by r3c**

### CODE REVIEW

**Review by fabienbk — COMMENTED** [review]
+2 !!! thx :)

**Comment by r3c** [comment]
I didn't know this was watched 😂

However I went for a timeout-based approach as I thought it would be more explicit to users, but @hexawyz convinced me of the benefit of counting "cycles" somehow (e.g. number of loop iterations, number of function calls, etc.). For example when writing unit tests I realized it was way too easy to hit a `StackOverflowException` with just a recursive function, even with a 1ms timeout 😅

So I'll likely revisit my approach and introduce some counter instead. If you want to do it, be my guest of course! 🙂

**Comment by r3c** [comment]
Let me know if this version works better for you @hexawyz 🙂 (just having a look at `CompiledDocumentTester.cs` should give you enough context)

**Review by hexawyz — APPROVED** [review]
This looks awesome! Thanks a lot 😊

**Pull request merged**
