### PR TITLE
Add RazorEngineCore benchmark

### PR DESCRIPTION
**Pull request by DanielStout5**
Had to change Product from a struct to a class to work around a bug in RazorEngineCore (which has been fixed but not released)

### CODE REVIEW

**Comment by r3c** [comment]
Thanks a lot! I'll update published benchmark after running it with this extra engine 👍

**Comment by r3c** [comment]
Hi again, I had a try running benchmark with this new engine. I also upgraded the benchmark to run using net6.0 so that may impact results compared to what to had, but here are the numbers I got for RazorEngineCore library:

- Create (template parsing time): 21,956.461 μs per operation (mean) ; Cottle time for the same test is 10.750 μs
- Render (template rendering time): 759.672 μs per operation (mean) ; Cottle time for the same test is 4.358 μs

I'm afraid these numbers would change the overall scale of the graph and make it hard to read. What do you think?

**Comment by DanielStout5** [comment]
Could the benchmark graph use a logarithmic scale?

That should still let the fast engines be differentiable.

**Comment by r3c** [comment]
> Could the benchmark graph use a logarithmic scale?
> 
> That should still let the fast engines be differentiable.

Well yes indeed that would work. However I'm not sure about changing the scale for a single engine while others have quite close figures. The main point of this benchmark was to give a rough idea of where Cottle stands compared to libraries similar in terms of feature set and performance. Maybe I can add a special "out of graph" section if you think it's worth seeing RazorEngineCore in this document?

**Comment by DanielStout5** [comment]
Sure - whatever you think was best!

The context here is that I was looking for a C# templating library which ideally uses Razor syntax, so I think it would be useful for others in the same situation to be able to compare as many libraries as possible in a single benchmark.

**Comment by r3c** [comment]
> Sure - whatever you think was best!
> 
> The context here is that I was looking for a C# templating library which ideally uses Razor syntax, so I think it would be useful for others in the same situation to be able to compare as many libraries as possible in a single benchmark.

The approach sounds useful and I really thank you for taking the time to send this 🙂 I'll try to see what could be the best option here and will keep you updated 👍

**Comment by r3c** [comment]
Update: I spent some time today upgrading benchmark so it runs against .net6.0 by default and changed the charts to use a logarithmic scale. For rendering time it works OK as RazorEngineCore shares a performance close to RazorLight and Scriban. However for parsing time the delta is too high even for a logarithmic scale and makes the whole graph hard to read with Cottle bar being only a few pixels tall. Here is what it looks like:

image

I'll play with it a bit more, but for now it seems the idea of switching to logarithmic scale isn't enough. Do you have any other suggestion?

**Comment by DanielStout5** [comment]
Hmm.. That doesn't look too bad to me - you can still distinguish the fast compiling libraries and tell that Cottle is the fastest.

Perhaps the y axis could have a higher base log? E.g. base 1000 instead of 10?

**Comment by r3c** [comment]
I followed your advice and mentioned `RazorEngineCore` in the benchmark page without showing it in the graph. Let me know if there is more you'd like me to do here 🙂

**Pull request closed without merging**
